Update handler to fix macro error
The handler `only` macro breaks when passing it a string variable now. Simply moving the downcase to outside the macro should be enough to fix it.

```
In lib/kemal/src/kemal/handler.cr:14:34

 14 | method_downcase = {{method.downcase}}
                                 ^-------
Error: undefined macro method 'Var#downcase'


In src/kemal-json-api/handler.cr:7:20

 7 | only [path], method
                  ^-----
Error: undefined macro method 'Var#downcase'
```